// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import {Construct} from "constructs";
import {CfnOutput, CfnParameter, CfnResource} from "aws-cdk-lib";
import {LogGroup, RetentionDays} from "aws-cdk-lib/aws-logs";
import {
  AccessLogFormat,
  GatewayResponse,
  LogGroupLogDestination,
  ResponseType,
  RestApi
} from "aws-cdk-lib/aws-apigateway";
import {CfnIPSet, CfnWebACL, CfnWebACLAssociation} from "aws-cdk-lib/aws-wafv2";
import {wrapManagedRuleSet} from "@aws-solutions-constructs/core";
import {addCfnGuardSuppressions} from "../helpers/add-cfn-guard-suppression";


type ApiProps = {
  region: string,
  allowListedIPRanges: CfnParameter,
  namespace: CfnParameter,
};

export class Api extends Construct {
  public readonly restApi: RestApi;
  public readonly apiGatewayUrl: string;

  constructor(scope: Construct, id: string, {region, allowListedIPRanges, namespace}: ApiProps) {
    super(scope, id);

    const prodLogGroup = new LogGroup(this, "ProdLogs", {
      retention: RetentionDays.TEN_YEARS
    });
    addCfnGuardSuppressions(prodLogGroup.node.defaultChild as CfnResource, ['CLOUDWATCH_LOG_GROUP_ENCRYPTED']);

    const api = new RestApi(this, 'AccountAssessmentForAWSOrganisationsApi', {
      restApiName: `AccountAssessmentForAWSOrganisationsApi-${namespace.valueAsString}`,
      deployOptions: {
        stageName: 'prod',
        accessLogDestination: new LogGroupLogDestination(prodLogGroup),
        accessLogFormat: AccessLogFormat.jsonWithStandardFields(),
        tracingEnabled: true
      },
      defaultCorsPreflightOptions: {
        allowOrigins: ['*'],
        allowMethods: ['*'],
        allowCredentials: false,
        allowHeaders: ['Content-Type', 'X-Amz-Date', 'Authorization', 'X-Api-Key', 'X-Amz-Security-Token', 'X-Amz-User-Agent']
      },
    });

    const responseHeaders = {
      'gatewayresponse.header.Access-Control-Allow-Origin': "'*'",
      'gatewayresponse.header.Access-Control-Allow-Headers': "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'",
      'gatewayresponse.header.Access-Control-Allow-Methods': "'GET,OPTIONS,POST,PUT,DELETE'"
    };

    // Add CORS headers to responses generated by Api Gateway itself. For responses by lambda functions, headers have to be set in the respective function.
    new GatewayResponse(this, `CORSResponse4xx`, {
      restApi: api,
      type: ResponseType.DEFAULT_4XX,
      responseHeaders: responseHeaders,
    });
    new GatewayResponse(this, `CORSResponse5xx`, {
      restApi: api,
      type: ResponseType.DEFAULT_5XX,
      responseHeaders: responseHeaders,
    });


    const ipSet = new CfnIPSet(this, 'IPSet', {
      addresses: allowListedIPRanges.valueAsList.map(it => it.trim()),
      ipAddressVersion: 'IPV4',
      scope: 'REGIONAL',
    });

    const cfnWebACL = new CfnWebACL(scope, `WebACL`, {
      defaultAction: {block: {}},
      scope: 'REGIONAL',
      visibilityConfig: {
        cloudWatchMetricsEnabled: true,
        metricName: "AccountAssessmentWebAclMetrics",
        sampledRequestsEnabled: true,
      },
      rules: [{
        name: "AllowlistRule",
        priority: 0,
        action: {allow: {}},
        visibilityConfig: {
          cloudWatchMetricsEnabled: true,
          metricName: "AccountAssessment-AllowlistMetric",
          sampledRequestsEnabled: true,
        },
        statement: {
          ipSetReferenceStatement: {
            arn: ipSet.attrArn,
          },
        },
      },
        wrapManagedRuleSet("AWSManagedRulesBotControlRuleSet", "AWS", 1),
        wrapManagedRuleSet("AWSManagedRulesKnownBadInputsRuleSet", "AWS", 2),
        wrapManagedRuleSet("AWSManagedRulesCommonRuleSet", "AWS", 3),
        wrapManagedRuleSet("AWSManagedRulesAnonymousIpList", "AWS", 4),
        wrapManagedRuleSet("AWSManagedRulesAmazonIpReputationList", "AWS", 5),
        wrapManagedRuleSet("AWSManagedRulesAdminProtectionRuleSet", "AWS", 6),
        wrapManagedRuleSet("AWSManagedRulesSQLiRuleSet", "AWS", 7)
      ]
    });

    new CfnWebACLAssociation(this, 'MyCfnWebACLAssociation', {
      resourceArn: api.deploymentStage.stageArn,
      webAclArn: cfnWebACL.attrArn,
    });

    const apiGatewayUrl = `https://${api.restApiId}.execute-api.${region}.amazonaws.com/prod`;
    new CfnOutput(this, 'ApiGatewayURL', {
      value: apiGatewayUrl,
    });

    this.restApi = api;
    this.apiGatewayUrl = apiGatewayUrl;
  }

}
